#!/bin/bash

#global vars
DEBUG=2
PROJROOT="/home/modem/www/"
RORSBIN="/ror/sbin"
GITLABPREFIX="git@127.0.0.1:root/"
DOCROOT="/directorydontexist"
DOCONLINE="/directorydontexist"
EXITSOP=0

####################### main function ##########################

# create a new project
newproject() {
  local projname=""
  local gitpath=""

  # We want sure that gitlab has well created project
  sleep 5

  # get options
  while (($# != 0)); do
    case "$1" in
      -n)
        shift
        projname="$1"
        shift
        ;;
      -u)
        shift
        GITLABPREFIX="$1"
        shift
        ;;
      -g)
        shift
        gitpath="${GITLABPREFIX}$1"
        shift
        ;;
      -*)
        shift
        ;;
    esac
  done

  DOCONLINE="${PROJROOT}${projname}/_online"

  [[ -d "${DOCONLINE}" ]] && rm -rf "${DOCONLINE}"
  /bin/mkdir -p "${DOCONLINE}"

  #make init commit
  pushd ${DOCONLINE} > /dev/null
  git clone "${gitpath}" .
  mkdir -p scripts
  cp "${RORSBIN}/files/gitignore_default" .gitignore
  cp "${RORSBIN}/files/postinstall.sh" scripts/
  chmod +x scripts/*.sh
  touch scripts/crontab
  git add  scripts .gitignore
  git commit -m "Init project"
  git push -u origin master
  popd > /dev/null

  # Clean temporary working directory
  /bin/rm -rf "${PROJROOT}${projname}"
}

echo "Parameters: $@"
newproject "$@"
