#!/bin/bash
#
# debian specific part for setup mvmc
# @author Eric Fehr (eric.fehr@publicis-modem.fr, @github: ricofehr)

# virtualbox install
install_vbox_debian() {
  output -q "Virtualbox Installation ..."
  sudo apt-get install -y --force-yes virtualbox
  (($?!=0)) && output -e 'Virtualbox installation has failed'
}

# vagrant install
install_vagrant_debian() {
  output -q "Vagrant Installation ..."
  curl -OsSL https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.2_x86_64.deb
  sudo dpkg -i --force-confdef vagrant_1.6.2_x86_64.deb
  (($?!=0)) && output -e 'Vagrant installation has failed'
  rm -f vagrant_1.6.2_x86_64.deb
  
  install_libvirt_debian
  install_vagrantlibvirt_debian
}

# libvirt install
install_libvirt_debian() {
  output -q "Libvirt Installation ..."
  
  sudo apt-get -y --force-yes install libvirt-daemon libvirt-bin virt-manager
  (($?!=0)) && output -e 'Libvirt installation has failed'
  sudo usermod -G libvirt -a $USER
  (($?!=0)) && output -e 'Cant add current user to libvirt group'

  sudo service libvirtd restart
}

# libvirt plugin for vagrant install
install_vagrantlibvirt_debian() {
  output -q "Libvirt Vagrant Plugin Installation ..."
  sudo apt-get -y --force-yes install libxslt-dev libxml2-dev libvirt-dev
  vagrant plugin install vagrant-libvirt
  (($?!=0)) && output -e 'Libvirt plugin for vagrant installation has failed'
}

# git install
install_git_debian() {
  output -q "Git Installation ..."
  sudo apt-get install -y --force-yes git
  (($?!=0)) && output -e 'Git installation has failed'
}

# kvm install
install_kvm_debian() {
  output -q "Kvm Installation ..."
  sudo apt-get install -y --force-yes qemu-kvm
  (($?!=0)) && output -e 'Kvm installation has failed'

  # reload kvm modules for avoid permission issue
  sudo modprobe -r kvm_intel
  sudo modprobe -r kvm
  (($?!=0)) && output -w 'Kvm reload is on error. Please reload kvm later and restart nova (uosnv) node after.'
  # kvm_amd ?
  sudo /bin/bash -c 'echo "options kvm_intel nested=1" > /etc/modprobe.d/kvm-intel.conf'
  sudo modprobe kvm
  sudo modprobe kvm_intel
  (($?!=0)) && output -w 'Kvm reload is on error. Please reload kvm later and restart nova (uosnv) node after.'
}

# nfs install
install_nfs_debian() {
  output -q "Nfs installation"
  sudo apt-get -y --force-yes install nfs-kernel-server
  (($?!=0)) && output -e 'Nfs installation has failed'
  sleep 5
  sudo service nfs-kernel-server restart
  (($?!=0)) && output -e 'Kvm start has failed'
}

# enable ip forward
ip_forward_debian() {
  # Enable ip forwarding on linux host
  output -q "Enable ip forwarding"
  sudo /bin/bash -c 'echo 1 > /proc/sys/net/ipv4/ip_forward'
  sudo /bin/bash -c 'echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf'
}

# debian prerequisites install
install_debian() {
  output -l "Your system is a Debian or Ubuntu"
  output -l "Some prerequisite must be installed"
  sleep 5

  # Install some needed packages
  sudo apt-get -y --force-yes install libmysqlclient-dev
  (($?!=0)) && output -w 'libmysqlclient-dev installation is on error. This library is needed by rails application'
  # Install rvm gpg key
  curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  
  install_git_debian
  install_kvm_debian
  install_vagrant_debian
  install_nfs_debian
  ip_forward_debian
}
