source 'https://rubygems.org'

gem 'rake', '11.2.2'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.9'
#gem 'sqlite3'
gem 'mysql2', '~> 0.4.8'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 3.2.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.2.2'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'active_model_serializers', '0.10.6'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.11'

# Use persistent connections
gem 'net-http-persistent', '2.9.4'

# Use debugger
# gem 'debugger', group: [:development, :test]

# Use devise for authentification part
gem 'devise'

# ror server
gem 'puma'

# gitlab api
gem 'gitlab', '~> 3.6.1'

# faraday restful library
gem 'faraday'

# gem for memcache store
gem 'dalli'

#yard for document code
gem 'yard'

# take screenshot from url
gem "webshot"
