source 'https://rubygems.org'

gem 'rake', '10.4.2'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.11'
#gem 'sqlite3'
gem 'mysql2', '~> 0.3.20'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'active_model_serializers', '0.9.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use persistent connections
gem 'net-http-persistent'

# Use debugger
# gem 'debugger', group: [:development, :test]

# Use devise for authentification part
gem 'devise'

# ror server
gem 'puma'

# gitlab api
gem 'gitlab', '~> 3.6.1'

# faraday restful library
gem 'faraday'

# gem for memcache store
gem 'dalli'

#yard for document code
gem 'yard'
