#!/bin/bash

BACKUPDATE="$(date +%y%m%d%H%M)"

pushd /tmp >/dev/null
mkdir mvmc-${BACKUPDATE}
mysqldump --default-character-set=utf8 --single-transaction --quick -u root -ptoor s_mvmc > mvmc-${BACKUPDATE}/s_mvmc.sql 2>/dev/null
(( $? != 0 )) && exit 1
rsync -az /home/mvmc mvmc-${BACKUPDATE}/ >/dev/null 2>&1
(( $? != 0 )) && exit 1
tar cvfz mvmc-${BACKUPDATE}.tar.gz mvmc-${BACKUPDATE} >/dev/null 2>&1
(( $? != 0 )) && exit 1
rm -rf mvmc-${BACKUPDATE}
popd >/dev/null

echo mvmc-${BACKUPDATE}.tar.gz