#!/bin/bash

# if we are root, exit
(( $UID == 0 )) && echo "please execute with modem user, not root" && exit 1

if [[ ! -f /ror/public/index.html ]] ||
[[ -n "$(find /home/nextdeploy/webui/app/. -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/config/. -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/public/. -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/package.json -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/bower.json -type f -mmin -5)" ]]; then
  pushd /tmp > /dev/null
  [[ -d webui ]] && rm -rf webui
  rsync -av --exclude .git /home/nextdeploy/webui .
  pushd webui > /dev/null
  npm install
  bower install
  ember build --environment %%EMBERENV%% --output-path /ror/public/
  [[ ! -f /ror/public/.keep ]] && touch /ror/public/.keep
  popd > /dev/null
  rm -rf webui
  popd > /dev/null
fi
