#!/bin/bash

# if we are root, exit
(( $UID == 0 )) && echo "please execute with modem user, not root" && exit 1

FORCE=0
[[ -n "$1" && "$1" = "--force" ]] && FORCE=1

[[ -n "$(find /tmp/.rebuildember -type f -mmin -10)" ]] && echo "rebuildember already executed" && exit 0
touch /tmp/.rebuildember

if (( FORCE == 1 )) ||
[[ ! -f /ror/public/index.html ]] ||
[[ -n "$(find /home/nextdeploy/webui/app/. -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/config/. -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/package.json -type f -mmin -5)" ]] ||
[[ -n "$(find /home/nextdeploy/webui/bower.json -type f -mmin -5)" ]]; then
  pushd /tmp > /dev/null
  [[ -d webui ]] && rm -rf webui
  rsync -av --exclude .git /home/nextdeploy/webui .
  pushd webui > /dev/null
  npm install
  bower install
  rm -f /ror/public/thumbs
  ember build --environment %%EMBERENV%% --output-path /ror/public/
  [[ ! -f /ror/public/.keep ]] && touch /ror/public/.keep
  rm -rf /ror/public/thumbs && ln -s /ror/thumbs /ror/public/thumbs
  popd > /dev/null
  rm -rf webui
  popd > /dev/null
fi

rm -f /tmp/.rebuildember
