#!/bin/bash

export HOME=/home/modem
export RUBY_VERSION=ruby-2.1.0
export MY_RUBY_HOME=/usr/local/rvm/rubies/ruby-2.1.0
export GEM_HOME=/usr/local/rvm/gems/ruby-2.1.0
export GEM_PATH=/usr/local/rvm/gems/ruby-2.1.0:/usr/local/rvm/gems/ruby-2.1.0@global
export PATH=/usr/local/rvm/gems/ruby-2.1.0/bin:/usr/local/rvm/gems/ruby-2.1.0@global/bin:/usr/local/rvm/rubies/ruby-2.1.0/bin:/usr/local/rvm/bin:/opt/ruby/bin/:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

if [[ -f /tmp/supervise.lock ]]; then
  exit
fi

touch /tmp/supervise.lock
ndeploy supervise
rm -f /tmp/supervise.lock
