#!/bin/bash
#
# Setup script for install mvmc platform on remote servers
# @author Eric Fehr (eric.fehr@publicis-modem.fr, @github: ricofehr)

PUPPETIP=''
PUPPETFQDN=''
PUPPETPORT=8114
OUT='out/remote.log'
BINSED='/bin/sed'
YES=0
DEBUG=1
DOMAIN=''

# use gsed if macosx
[[ -f /usr/bin/sw_vers ]] && BINSED='/usr/local/bin/gsed'

source scripts/inc/utils

# Redirect output to log file
if [[ -n "$OUT" ]]; then
  rm -f $OUT
  exec 3>&1 4>&2 1>>$OUT 2>&1
fi

# Some intoduction words
welcome_step() {
  output -l -q "This script is an help for install mvmc on remote servers."
  output -l -q "You need 4 servers for install openstack nodes, 1 server for the manager node (gitlab, rest api, dns) and one empty puppet service up somewhere outside this 5 servers."
  output -l -q "Your remote servers need to be accessed by ssh with root user."
  confirm "Continue ?"
  echo -en "\n\n"
}

# Prerequisites
prerequisites() {
  local exteth=''
  local masqeth=''
  local publicnetwork=''
  local gateway_ip=''
  local startip=''
  local endip=''
  local mvmcuri=''
  local mvmcsuf=''
  local gitlaburi=''

  # temporary folder used by remote install
  rm -rf tmp/remote
  mkdir tmp/remote
  mkdir tmp/remote/os
  mkdir tmp/remote/mvmc

  # duplicate yaml for remote setting
  cp vagrant/os/hiera/os/uos* tmp/remote/os/
  cp vagrant/mvmc/hiera/mvmc/mvmc* tmp/remote/mvmc/
  cp vagrant/os/hiera/global.yaml.dist tmp/remote/os/global.yaml
  cp vagrant/mvmc/hiera/global.yaml.dist tmp/remote/mvmc/global.yaml
  cp vagrant/modules/pm/files/hosts/hosts tmp/remote/

  # get the publicprefix
  output -q -l "The openstack public network (default is 192.168.71) ?"
  read publicprefix
  [[ -z "$publicprefix" ]] && publicprefix='192.168.71'

  # get the data prefix
  output -q -l "The openstack data network (default is 172.16.71) ?"
  read dataprefix
  [[ -z "$dataprefix" ]] && dataprefix='172.16.71'

  # get the api prefix
  output -q -l "The openstack api network (default is 192.168.70) ?"
  read apiprefix
  [[ -z "$apiprefix" ]] && apiprefix='192.168.70'

  # get the management prefix
  output -q -l "The openstack management network (default is 172.16.70) ?"
  read managementprefix
  [[ -z "$managementprefix" ]] && managementprefix='172.16.70'

  # the public network device
  output -q -l "The ethernet device associated on neutron to the openstack public network (default is eth1) ?"
  read exteth
  [[ -z "$exteth" ]] && exteth='eth1'

  # the external device
  output -q -l "The ethernet device associated to the default route on neutron ? (default is eth0)"
  read masqeth
  [[ -z "$masqeth" ]] && masqeth='eth0'

  # the local domain for the 5 mvmc servers
  output -q -l "The local domain for the 5 mvmc servers ? (default is nothing)"
  read DOMAIN
  [[ -z "$DOMAIN" ]] && DOMAIN='' 

  # the mvmc webui
  output -q -l "The manager mvmc uri ? (default is mvmc.${DOMAIN})"
  read mvmcuri
  [[ -z "$mvmcuri" ]] && mvmcuri="mvmc.$DOMAIN"

  # the gitlab webui
  output -q -l "The gitlab uri ? (default is gitlab.${DOMAIN})"
  read gitlaburi
  [[ -z "$gitlaburi" ]] && gitlaburi="gitlab.${DOMAIN}"

  # the common subdomain for vm endpoint
  output -q -l "The common wildcard subdomain for the vms ? (default is os.${DOMAIN})"
  read mvmcsuf
  [[ -z "$mvmcsuf" ]] && mvmcsuf="os.${DOMAIN}" 

  # get from input the puppetmaster ip
  output -q -l "Puppet-master ip ?"
  read PUPPETIP

  output -q -l "Puppet-master fqdn ?"
  read PUPPETFQDN

  output -q -l "Puppet-master port ?"
  read PUPPETPORT

  # add extra line into hosts file
  echo "${PUPPETIP} ${PUPPETFQDN}" >> tmp/remote/hosts

  # create puppet.conf file
  cat > tmp/remote/puppet.conf << EOF
[main]
logdir=/var/log/puppet
vardir=/var/lib/puppet
ssldir=/var/lib/puppet/ssl
rundir=/var/run/puppet
factpath=$vardir/lib/facter
ordering=manifest

[master]
ssl_client_header = SSL_CLIENT_S_DN
ssl_client_verify_header = SSL_CLIENT_VERIFY

[agent]
server=${PUPPETFQDN}
masterport=${PUPPETPORT}
report=true
pluginsync=true
ssldir=/var/lib/puppet/sslagent
EOF


  # prepare global.yaml file
  # os part
  $BINSED -i "s;%%PUBPREFIX%%;${publicprefix};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%DATAPREFIX%%;${dataprefix};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%APIPREFIX%%;${apiprefix};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%MANAGEMENTPREFIX%%;${managementprefix};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%EXTDEV%%;${exteth};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%PUBDEV%%;${masqeth};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%NOVAHV%%;kvm;" tmp/remote/os/global.yaml
  $BINSED -i "s;%%MVMCURI%%;${mvmcuri};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%MVMCSUF%%;${mvmcsuf};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%GITLABURI%%;${gitlaburi};" tmp/remote/os/global.yaml
  $BINSED -i "s;%%GITLABNS%%;${gitlaburi%%/*};" tmp/remote/os/global.yaml
  # mvmc part
  $BINSED -i "s;%%PUBPREFIX%%;${publicprefix};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%DATAPREFIX%%;${dataprefix};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%APIPREFIX%%;${apiprefix};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%MANAGEMENTPREFIX%%;${managementprefix};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%MVMCURI%%;${mvmcuri};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%MVMCSUF%%;${mvmcsuf};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%GITLABURI%%;${gitlaburi};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%GITLABNS%%;${gitlaburi%%/*};" tmp/remote/mvmc/global.yaml
  $BINSED -i "s;%%RAILSENV%%;production;" tmp/remote/mvmc/global.yaml  

  # merge the 2 global files
  cat tmp/remote/os/global.yaml tmp/remote/mvmc/global.yaml | sort | uniq > tmp/remote/global.yaml
  scp tmp/remote/global.yaml root@${PUPPETIP}:/var/lib/hiera/

  # prepare rails production config file
  cp ror/config/environments/production.rb.dist tmp/remote/mvmc/production.rb

  # prepare rails config file
  $BINSED -i "s;%%PUBPREFIX%%;${publicprefix};" tmp/remote/mvmc/production.rb
  $BINSED -i "s;%%MVMCSUF%%;${mvmcsuf};" tmp/remote/mvmc/production.rb
  $BINSED -i "s;%%MVMCURI%%;${mvmcuri};" tmp/remote/mvmc/production.rb
  $BINSED -i "s;%%GITLABNS%%;${gitlaburi%%/*};" tmp/remote/mvmc/production.rb
  
  output -l -q "On controller openstack node, please configure this 3 private ips: ${managementprefix}.70, ${dataprefix}.70, ${apiprefix}.70"
  output -l -q "On neutron openstack node, please configure this 4 private ips: ${publicprefix}.71, ${managementprefix}.71, ${dataprefix}.71, ${apiprefix}.71"
  output -l -q "On glance openstack node, please configure this 2 private ips: ${managementprefix}.72, ${apiprefix}.72"
  output -l -q "On compute openstack node, please configure this 3 private ips: ${managementprefix}.75, ${dataprefix}.75, ${apiprefix}.75"
  output -l -q "On mvmc manager node, please configure this 3 private ips: ${publicprefix}.60, ${managementprefix}.60, ${apiprefix}.60"
  confirm "Waiting this installations are done ... Continue ?"
  echo -en "\n\n"
}

# Upload puppet templates for openstack and manager install
remote_puppet() {
  
  output -q 'Working on remote puppet master'
  # install puppetmaster if we are on debian / ubuntu
  ssh root@${PUPPETIP} '[[ -x /etc/debian_version ]] && apt-get install puppetmaster'
  # clean puppet master
  ssh root@${PUPPETIP} 'rm -rf /etc/puppet/modules'
  ssh root@${PUPPETIP} 'rm -rf /var/lib/hiera && mkdir /var/lib/hiera'
  ssh root@${PUPPETIP} 'puppet cert clean --all'

  # rsync puppet modules (rsync here but a git clone into puppet node should be better)
  rsync -avzPessh vagrant/modules root@${PUPPETIP}:/etc/puppet/
  # create site.pp on remote puppet
  echo 'hiera_include("classes")' > tmp/remote/site.pp
  rsync -avzPessh tmp/remote/site.pp root@${PUPPETIP}:/etc/puppet/manifests/site.pp

  # create hiera.yml file
  cat > tmp/remote/hiera.yaml << EOF
---
:backends:
  - yaml
:yaml:
  :datadir: /var/lib/hiera
:hierarchy:
  - "%{clientcert}"
  - "%{environment}"
  - global
EOF
  rsync -avzPessh tmp/remote/hiera.yaml root@${PUPPETIP}:/etc/puppet/hiera.yaml
  scp tmp/remote/global.yaml root@${PUPPETIP}:/var/lib/hiera/
  
  # rsync default hosts file
  rsync -avzPessh tmp/remote/hosts root@${PUPPETIP}:/etc/puppet/modules/pm/files/hosts/
  # change owner of puppet modules folder
  ssh root@${PUPPETIP} 'chown -R puppet: /etc/puppet/modules'
  # restart the puppet master daemon
  ssh root@${PUPPETIP} 'service puppetmaster restart'
}

prepare_node() {
  # ip is the first parameter, fqdn the second
  local remote_ip="$1"
  local fqdn="$2"

  output -q "Working on $fqdn node"

  # set the fqdn
  ssh root@${remote_ip} "hostname ${fqdn}; echo '127.0.0.1 ${fqdn}' > /etc/hosts; echo ${fqdn} > /etc/hostname"
  ssh root@${remote_ip} 'sed -i "s/^domain.*//;s/^search.*//" /etc/resolv.conf'

  # set locale
  ssh root@${remote_ip} 'echo LANG=en_US.UTF-8 > /etc/default/locale'
  ssh root@${remote_ip} 'echo LC_ALL=en_US.UTF-8 >> /etc/default/locale'

  # add puppetmaster into hosts file
  ssh root@${remote_ip} "echo '${PUPPETIP} ${PUPPETFQDN}' >> /etc/hosts"
  
  # reboot remote uosc
  ssh root@${remote_ip} "reboot"

  # reboot and get puppet repo
  confirm 'Server is going to reboot. Please waiting that he is up again and continue with puppet install'

  # apt-get update
  ssh root@${remote_ip} "apt-get update"

  # install puppet agent
  ssh root@${remote_ip} "apt-get install -y --force-yes puppet"

  # puppet.conf file
  rsync -avzPessh tmp/remote/puppet.conf root@${remote_ip}:/etc/puppet/
}

# make install process for one node
install_osnode() {
  # fqdn the function parameter
  local nodename="$1"
  local fqdn="$1"
  [[ -n "$DOMAIN" ]] && fqdn="${fqdn}.${DOMAIN}"

  # get the ip
  output -q -l "The ip for $fqdn controller node ?"
  read remote_ip
  
  # set local, hosts and install puppet
  prepare_node $remote_ip $fqdn

  # synchro hiera file
  scp tmp/remote/os/${nodename}.yaml root@${PUPPETIP}:/var/lib/hiera/${fqdn}.yaml

  # synchro fw and hosts file
  rsync -avzPessh vagrant/modules/pm/files/fw/fw_${nodename} root@${PUPPETIP}:/etc/puppet/modules/pm/files/fw/fw_${fqdn}
  
  # enable puppet on the remote node and validate on puppetmaster
  ssh root@${remote_ip} 'puppet agent --test'
  sleep 3
  ssh root@${PUPPETIP} 'puppet cert sign --all'
  ssh root@${remote_ip} 'puppet agent --enable'
  output -q "Installation on progress for $fqdn node, please waiting (>20min, press enter if nothing happend after this time) ..."
  ssh root@${remote_ip} 'puppet agent --test; service puppet stop;'

  output -q "Installation is done for $fqdn node."
  confirm "Continue ?"
}

# Install mvmc manager node
install_mvmc() {
  local fqdn='mvmc'
  [[ -n "$DOMAIN" ]] && fqdn="${fqdn}.${DOMAIN}"

  # get the ip
  output -q -l 'The ip for mvmc manager node ?'
  read remote_ip

  # update MVMCIP into production.rb
  $BINSED -i "s;%%MVMCIP%%;${remote_ip};" tmp/remote/mvmc/production.rb

  # prepare puppet.conf for master node on mvmc
  # create puppet.conf file
  cat > tmp/remote/puppet_mvmc.conf << EOF
[main]
dns_alt_names = mvmc
logdir=/var/log/puppet
vardir=/var/lib/puppet
ssldir=/var/lib/puppet/ssl
rundir=/var/run/puppet
factpath=$vardir/lib/facter
user=modem
group=modem
ordering=manifest
hiera_config=/etc/hiera.yaml

[master]
ssl_client_header = SSL_CLIENT_S_DN
ssl_client_verify_header = SSL_CLIENT_VERIFY

[agent]
server=${PUPPETFQDN}
masterport=${PUPPETPORT}
report=true
pluginsync=true
ssldir=/var/lib/puppet/sslagent
EOF
  rsync -avzPessh tmp/remote/puppet_mvmc.conf root@${PUPPETIP}:/etc/puppet/modules/pm/files/puppet/puppet.conf

  # setting local, hosts and install puppet
  prepare_node $remote_ip $fqdn

  # clone project into tmp folder
  mkdir tmp/mvmcgit
  pushd tmp/mvmcgit > /dev/null
  ssh root@${remote_ip} 'mkdir -p /home/mvmc'
  git clone --recursive git@github.com:ricofehr/mvmc.git .
  rsync -avzPessh . root@${remote_ip}:/home/mvmc/
  ssh root@${remote_ip} 'ln -sf /home/mvmc/puppet /puppet'
  ssh root@${remote_ip} 'ln -sf /home/mvmc/ror /ror'
  ssh root@${remote_ip} 'ln -sf /home/mvmc/out /out'
  ssh root@${remote_ip} 'ln -sf /home/mvmc/ror/hiera /hiera'
  popd > /dev/null
  rm -rf tmp/mvmcgit

  # rsync rails app (git clone on remote server should be better)
  rsync -avzPessh tmp/remote/mvmc/production.rb root@${remote_ip}:/ror/config/environments/

  # synchro hiera file
  scp tmp/remote/mvmc/mvmc.yaml root@${PUPPETIP}:/var/lib/hiera/${fqdn}.yaml

  # synchro fw and hosts file
  rsync -avzPessh vagrant/modules/pm/files/fw/fw_mvmc root@${PUPPETIP}:/etc/puppet/modules/pm/files/fw/fw_${fqdn}
  
  # enable puppet on the remote node and validate on puppetmaster
  ssh root@${remote_ip} 'puppet agent --test'
  sleep 3
  ssh root@${PUPPETIP} 'puppet cert sign --all'
  ssh root@${remote_ip} 'puppet agent --enable'
  output -q "Installation on progress for $fqdn node, please waiting (>20min, press enter if nothing happend after this time) ..."
  ssh root@${remote_ip} 'puppet agent --test; service puppet stop'

  output -q "Installation is done for $fqdn node."
  confirm "Continue ?"
}

welcome_step
prerequisites

output -l -q 'Remote puppet installation ? (y/n)'
read response
[[ "$response" = "y" ]] && remote_puppet

output -l -q 'Openstack controller installation ? (y/n)'
read response
[[ "$response" = "y" ]] && install_osnode uosc

output -l -q 'Openstack neutron installation ? (y/n)'
read response
[[ "$response" = "y" ]] && install_osnode uosnt

output -l -q 'Openstack glance installation ? (y/n)'
read response
[[ "$response" = "y" ]] && install_osnode uosst

output -l -q 'Openstack compute installation ? (y/n)'
read response
[[ "$response" = "y" ]] && install_osnode uosnv

output -l -q 'Mvmc manager installation ? (y/n)'
read response
[[ "$response" = "y" ]] && install_mvmc
