#!/bin/bash
#
# Start script for launch mvmc platform
# @author Eric Fehr (eric.fehr@publicis-modem.fr, @github: ricofehr)

# Include some usable functions
source scripts/inc/utils

# define provider
HVISOR="$(get_hypervisor)"
DNSIP='192.168.171.60'

while (($# > 0)); do
  case "$1" in
    -n)
      shift
      DNSIP="$1"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

# little ugly but sometimes in ubuntu statd is not starting
ps aux | grep statd | grep -v grep > /dev/null
(($?!=0)) && sudo rpc.statd

# Start openstack nodes
pushd vagrant/os > /dev/null
vagrant up --provider=${HVISOR}
vagrant up uosnt --provider=${HVISOR}
vagrant up uosst --provider=${HVISOR}
vagrant up uosnv --provider=${HVISOR}
popd > /dev/null

# Start manager node
pushd vagrant/mvmc > /dev/null
vagrant up --provider=${HVISOR}
popd > /dev/null

# Start mc2 node
pushd vagrant/mc2 > /dev/null
vagrant up --provider=${HVISOR}
popd > /dev/null

# Wait that manager is up and target dns resolv to manger node
sleep 30
cp /etc/resolv.conf tmp/resolv.conf.mvmc
sudo /bin/bash -c "echo 'nameserver ${DNSIP}' > /etc/resolv.conf"
