#!/bin/bash
#
# Start script for launch nextdeploy platform
# @author Eric Fehr (ricofehr@nextdeploy.io, @github: ricofehr)

# Include some usable functions
source scripts/inc/utils

# define provider
HVISOR="$(get_hypervisor)"
DNSIP='192.168.171.60'
# endpoint for nextdeploy
NEXTDEPLOYURI='nextdeploy.local'

while (($# > 0)); do
  case "$1" in
    -n)
      shift
      DNSIP="$1"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

# little ugly but sometimes in ubuntu statd is not starting
ps aux | grep statd | grep -v grep > /dev/null
(( $? != 0 )) && sudo rpc.statd &

# Start mc2 node
pushd vagrant/ndc2 > /dev/null
vagrant up --provider=${HVISOR}
popd > /dev/null

# Start openstack nodes
pushd vagrant/os > /dev/null
vagrant up --provider=${HVISOR}
vagrant up uosnt --provider=${HVISOR}
vagrant up uosst --provider=${HVISOR}
vagrant up uosnv --provider=${HVISOR}
popd > /dev/null

# Start manager node
pushd vagrant/nextdeploy > /dev/null
vagrant up --provider=${HVISOR}
popd > /dev/null

cat <<EOF
The NextDeploy installation for local env uses self-signed ssl certificates.
For avoid some browser security restrictions, please open these urls on your browser once
https://api.${NEXTDEPLOYURI}/
https://grafana.${NEXTDEPLOYURI}/
https://vnc.${NEXTDEPLOYURI}/

After that, you can use the "webui" without ssl issues
https://ui.${NEXTDEPLOYURI}/
EOF

# Wait that manager is up and target dns resolv to manger node
#sleep 30
#cp /etc/resolv.conf tmp/resolv.conf.nextdeploy
#sudo /bin/bash -c "echo 'nameserver ${DNSIP}' > /etc/resolv.conf"
