#!/bin/bash
#
# Stop script for halt nextdeploy platform
# @author Eric Fehr (eric.fehr@publicis-modem.fr, @github: ricofehr)

# Include some usable functions
source scripts/inc/utils

# Stop openstack nodes
pushd vagrant/os > /dev/null
vagrant halt
popd > /dev/null

# Stop manager node
pushd vagrant/nextdeploy > /dev/null
vagrant halt
popd > /dev/null

# Stop mc2 node
pushd vagrant/ndc2 > /dev/null
vagrant halt
popd > /dev/null

# Rollback resolv.conf
#[[ -f tmp/resolv.conf.nextdeploy ]] && reset_dnsserver tmp/resolv.conf.nextdeploy
#rm -f tmp/resolv.conf.nextdeploy
